class_name Layers

const WORLD_SOLID = 1
const ACTOR_BODY = 2
const AREA_SENSOR = 3
const LOOT = 4
const PLAYER_HURTBOX = 10
const PLAYER_HITBOX = 11
const PLAYER_PICKUPBOX = 12
const ENEMY1_HURTBOX = 15
const ENEMY1_HITBOX = 16
const ENEMY1_PICKUPBOX = 17
const ENEMY2_HURTBOX = 20
const ENEMY2_HITBOX = 21
const ENEMY2_PICKUPBOX = 22
const NAV_WALK = 1
