class_name Layers
## Purpose: Defines physics and navigation layer constants.

# Physics
const WORLD_SOLID = 1
const ACTOR_BODY = 2
const AREA_SENSOR = 3
const LOOT = 4
const FLOCK = 5
const PLAYER_HURTBOX = 10
const PLAYER_HITBOX = 11
const PLAYER_PICKUPBOX = 12
const PLAYER_TARGETING_SENSOR = 13
const PLAYER_HOSTILE_SENSOR = 14
const ENEMY1_HURTBOX = 17
const ENEMY1_HITBOX = 18
const ENEMY1_PICKUPBOX = 19
const ENEMY1_TARGETING_SENSOR = 20
const ENEMY1_HOSTILE_SENSOR = 21
const ENEMY2_HURTBOX = 23
const ENEMY2_HITBOX = 24
const ENEMY2_PICKUPBOX = 25
const ENEMY2_TARGETING_SENSOR = 26
const ENEMY2_HOSTILE_SENSOR = 27
# Nav
const NAV_WALK = 1
